import unittest
import os
import shutil
import tempfile
import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

from axiomlm.train import train
from axiomlm.engine.export import export_checkpoint_to_hf


class TestSystemE2E(unittest.TestCase):
    def setUp(self):
        # Force CPU to prevent CI OOMs and ensure deterministic testing
        self.original_mps_is_available = None
        if hasattr(torch.backends, "mps"):
            self.original_mps_is_available = torch.backends.mps.is_available

            def _mock_is_available():
                return False

            _mock_is_available.__wrapped__ = getattr(
                self.original_mps_is_available, "__wrapped__", None
            )
            torch.backends.mps.is_available = _mock_is_available

        self.tmp_data_dir = tempfile.mkdtemp()
        self.tmp_export_dir = tempfile.mkdtemp()

        # Create dataset large enough for total_batch_size=2048 (requires at least 100k for safe padding)
        synthetic_tokens = np.random.randint(0, 50257, size=100_000, dtype=np.uint16)
        synth_path = os.path.join(self.tmp_data_dir, "train_0000.bin")
        synthetic_tokens.tofile(synth_path)

        val_path = os.path.join(self.tmp_data_dir, "val_0000.bin")
        synthetic_tokens[:10000].tofile(val_path)

    def tearDown(self):
        if self.original_mps_is_available:
            torch.backends.mps.is_available = self.original_mps_is_available

        shutil.rmtree(self.tmp_data_dir, ignore_errors=True)
        shutil.rmtree(self.tmp_export_dir, ignore_errors=True)

        # Clean up checkpoints generated by train()
        if os.path.exists("checkpoints"):
            shutil.rmtree("checkpoints", ignore_errors=True)

    def test_end_to_end_training_and_hf_export(self):
        """
        System Test:
        1. Runs the full pretraining loop for 2 steps.
        2. Exports the generated checkpoint to Hugging Face format.
        3. Loads the exported weights using AxiomLM Inference Engine.
        """
        # 1. Run the training loop (total_batch_size=2048 means B=2, T=1024 on CPU)
        train(
            max_steps=2,
            total_batch_size=2048,
            eval_interval=10,
            sample_interval=10,
            save_interval=1,
            architecture="modern",
            optimizer_type="muon",
            data_dir=self.tmp_data_dir,
        )

        ckpt_path = "checkpoints/model_latest.pt"
        self.assertTrue(
            os.path.exists(ckpt_path), "Training loop failed to save model_latest.pt"
        )

        # 2. Export to Hugging Face
        export_checkpoint_to_hf(
            checkpoint_path=ckpt_path,
            output_dir=self.tmp_export_dir,
            model_name="AxiomLM-E2E-Test",
        )

        self.assertTrue(
            os.path.exists(os.path.join(self.tmp_export_dir, "model.safetensors"))
        )
        self.assertTrue(
            os.path.exists(os.path.join(self.tmp_export_dir, "config.json"))
        )

        # 3. Reload using standard Hugging Face transformers
        try:
            hf_model = AutoModelForCausalLM.from_pretrained(self.tmp_export_dir)
            self.assertIsNotNone(hf_model)

            # Verify a simple forward pass in standard HF format
            dummy_input = torch.tensor([[1, 2, 3]])
            output = hf_model(dummy_input)
            self.assertIsNotNone(output.logits)

            # Verify standard HF tools can load the exported tokenizer
            hf_tokenizer = AutoTokenizer.from_pretrained(self.tmp_export_dir)
            self.assertIsNotNone(hf_tokenizer)

        except Exception as e:
            self.fail(
                f"Hugging Face transformers failed to load the exported model or tokenizer: {e}"
            )


if __name__ == "__main__":
    unittest.main()
